In [2]:
import pandas as pd
import os
import glob

In [3]:
os.chdir(r'C:\Users\henry\OneDrive\Documents\school_performance_data\school_dem_info\school_dem_data_files')

In [4]:
csv = glob.glob('*.csv')

In [5]:
csv

['ccd_sch_029_1516_w_1a_011717.csv',
 'ccd_sch_029_1718_w_0a_03302018.csv',
 'ccd_sch_029_1718_w_1a_083118.csv',
 'ccd_sch_029_1819_w_0a_04082019.csv',
 'ccd_sch_033_1516_w_1a_011717.csv',
 'ccd_sch_033_1617_l_1a_112117.csv',
 'ccd_sch_033_1718_l_1a_083118.csv',
 'ccd_sch_033_1819_l_1a_091019.csv',
 'ccd_sch_052_1516_w_1a_011717.csv',
 'ccd_SCH_052_1617_l_1a_11212017.csv',
 'CCD_SCH_059_1516_W_1a_011717.csv',
 'ccd_sch_059_1617_l_1a_11212017.csv',
 'ccd_sch_059_1819_l_1a_091019.csv',
 'ccd_sch_129_1516_w_1a_011717.csv',
 'ccd_sch_129_1617_w_1a_11212017.csv',
 'ccd_sch_129_1819_w_1a_091019.csv',
 'lea-homeless-enrolled-sy2013-14-pub.csv',
 'lea-homeless-enrolled-sy2014-15.csv',
 'lea-homeless-enrolled-sy2015-16.csv',
 'lea-homeless-enrolled-sy2016-17.csv',
 'lea-homeless-enrolled-sy2017-18.csv',
 'lea-homeless-enrolled-sy2018-19-long.csv',
 'lea-homeless-enrolled-sy2018-19-wide.csv']

In [14]:
school_dem09 = pd.read_sas('sc091a.sas7bdat', format = 'sas7bdat', encoding='iso-8859-1')

In [17]:
list(school_dem09.columns)

['NCESSCH',
 'FIPST',
 'LEAID',
 'SCHNO',
 'STID09',
 'SEASCH09',
 'LEANM09',
 'SCHNAM09',
 'PHONE09',
 'MSTREE09',
 'MCITY09',
 'MSTATE09',
 'MZIP09',
 'MZIP409',
 'LSTREE09',
 'LCITY09',
 'LSTATE09',
 'LZIP09',
 'LZIP409',
 'TYPE09',
 'STATUS09',
 'ULOCAL09',
 'LATCOD09',
 'LONCOD09',
 'CONUM09',
 'CONAME09',
 'CDCODE09',
 'FTE09',
 'GSLO09',
 'GSHI09',
 'LEVEL09',
 'TITLEI09',
 'STITLI09',
 'MAGNET09',
 'CHARTR09',
 'SHARED09',
 'BIES09',
 'FRELCH09',
 'REDLCH09',
 'TOTFRL09',
 'RACECAT09',
 'PK09',
 'AMPKM09',
 'AMPKF09',
 'ASPKM09',
 'ASPKF09',
 'HIPKM09',
 'HIPKF09',
 'BLPKM09',
 'BLPKF09',
 'WHPKM09',
 'WHPKF09',
 'HPPKM09',
 'HPPKF09',
 'TRPKM09',
 'TRPKF09',
 'KG09',
 'AMKGM09',
 'AMKGF09',
 'ASKGM09',
 'ASKGF09',
 'HIKGM09',
 'HIKGF09',
 'BLKGM09',
 'BLKGF09',
 'WHKGM09',
 'WHKGF09',
 'HPKGM09',
 'HPKGF09',
 'TRKGM09',
 'TRKGF09',
 'G0109',
 'AM01M09',
 'AM01F09',
 'AS01M09',
 'AS01F09',
 'HI01M09',
 'HI01F09',
 'BL01M09',
 'BL01F09',
 'WH01M09',
 'WH01F09',
 'HP01M09',
 'HP01F09',
 'TR01M09',
 'TR01F09',
 'G0209',
 'AM02M09',
 'AM02F09',
 'AS02M09',
 'AS02F09',
 'HI02M09',
 'HI02F09',
 'BL02M09',
 'BL02F09',
 'WH02M09',
 'WH02F09',
 'HP02M09',
 'HP02F09',
 'TR02M09',
 'TR02F09',
 'G0309',
 'AM03M09',
 'AM03F09',
 'AS03M09',
 'AS03F09',
 'HI03M09',
 'HI03F09',
 'BL03M09',
 'BL03F09',
 'WH03M09',
 'WH03F09',
 'HP03M09',
 'HP03F09',
 'TR03M09',
 'TR03F09',
 'G0409',
 'AM04M09',
 'AM04F09',
 'AS04M09',
 'AS04F09',
 'HI04M09',
 'HI04F09',
 'BL04M09',
 'BL04F09',
 'WH04M09',
 'WH04F09',
 'HP04M09',
 'HP04F09',
 'TR04M09',
 'TR04F09',
 'G0509',
 'AM05M09',
 'AM05F09',
 'AS05M09',
 'AS05F09',
 'HI05M09',
 'HI05F09',
 'BL05M09',
 'BL05F09',
 'WH05M09',
 'WH05F09',
 'HP05M09',
 'HP05F09',
 'TR05M09',
 'TR05F09',
 'G0609',
 'AM06M09',
 'AM06F09',
 'AS06M09',
 'AS06F09',
 'HI06M09',
 'HI06F09',
 'BL06M09',
 'BL06F09',
 'WH06M09',
 'WH06F09',
 'HP06M09',
 'HP06F09',
 'TR06M09',
 'TR06F09',
 'G0709',
 'AM07M09',
 'AM07F09',
 'AS07M09',
 'AS07F09',
 'HI07M09',
 'HI07F09',
 'BL07M09',
 'BL07F09',
 'WH07M09',
 'WH07F09',
 'HP07M09',
 'HP07F09',
 'TR07M09',
 'TR07F09',
 'G0809',
 'AM08M09',
 'AM08F09',
 'AS08M09',
 'AS08F09',
 'HI08M09',
 'HI08F09',
 'BL08M09',
 'BL08F09',
 'WH08M09',
 'WH08F09',
 'HP08M09',
 'HP08F09',
 'TR08M09',
 'TR08F09',
 'G0909',
 'AM09M09',
 'AM09F09',
 'AS09M09',
 'AS09F09',
 'HI09M09',
 'HI09F09',
 'BL09M09',
 'BL09F09',
 'WH09M09',
 'WH09F09',
 'HP09M09',
 'HP09F09',
 'TR09M09',
 'TR09F09',
 'G1009',
 'AM10M09',
 'AM10F09',
 'AS10M09',
 'AS10F09',
 'HI10M09',
 'HI10F09',
 'BL10M09',
 'BL10F09',
 'WH10M09',
 'WH10F09',
 'HP10M09',
 'HP10F09',
 'TR10M09',
 'TR10F09',
 'G1109',
 'AM11M09',
 'AM11F09',
 'AS11M09',
 'AS11F09',
 'HI11M09',
 'HI11F09',
 'BL11M09',
 'BL11F09',
 'WH11M09',
 'WH11F09',
 'HP11M09',
 'HP11F09',
 'TR11M09',
 'TR11F09',
 'G1209',
 'AM12M09',
 'AM12F09',
 'AS12M09',
 'AS12F09',
 'HI12M09',
 'HI12F09',
 'BL12M09',
 'BL12F09',
 'WH12M09',
 'WH12F09',
 'HP12M09',
 'HP12F09',
 'TR12M09',
 'TR12F09',
 'UG09',
 'AMUGM09',
 'AMUGF09',
 'ASUGM09',
 'ASUGF09',
 'HIUGM09',
 'HIUGF09',
 'BLUGM09',
 'BLUGF09',
 'WHUGM09',
 'WHUGF09',
 'HPUGM09',
 'HPUGF09',
 'TRUGM09',
 'TRUGF09',
 'MEMBER09',
 'AM09',
 'AMALM09',
 'AMALF09',
 'ASIAN09',
 'ASALM09',
 'ASALF09',
 'HISP09',
 'HIALM09',
 'HIALF09',
 'BLACK09',
 'BLALM09',
 'BLALF09',
 'WHITE09',
 'WHALM09',
 'WHALF09',
 'PACIFIC09',
 'HPALM09',
 'HPALF09',
 'TR09',
 'TRALM09',
 'TRALF09',
 'TOTETH09',
 'PUPTCH09']

In [29]:
school_dem09[['FRELCH09','REDLCH09','TOTFRL09']]

        FRELCH09  REDLCH09  TOTFRL09
0           -2.0      -2.0      -2.0
1           -2.0      -2.0      -2.0
2           -2.0      -2.0      -2.0
3           -2.0      -2.0      -2.0
4           -2.0      -2.0      -2.0
...          ...       ...       ...
103954     411.0      -1.0     411.0
103955     448.0      -1.0     448.0
103956     425.0      -1.0     425.0
103957     582.0      -1.0     582.0
103958     603.0      -1.0     603.0

[103959 rows x 3 columns]

In [33]:
school_dem09[['LATCOD09','LONCOD09','CONAME09']]

         LATCOD09   LONCOD09           CONAME09
0       33.699128 -86.606673   JEFFERSON COUNTY
1       31.879475 -85.247080     BARBOUR COUNTY
2       32.387825 -86.100736  MONTGOMERY COUNTY
3       32.387740 -86.100481  MONTGOMERY COUNTY
4       32.378760 -86.083164  MONTGOMERY COUNTY
...           ...        ...                ...
103954  18.353129 -65.017356  ST. THOMAS ISLAND
103955  18.325332 -64.787245    ST. JOHN ISLAND
103956  18.355057 -64.898732  ST. THOMAS ISLAND
103957  18.340859 -64.927156  ST. THOMAS ISLAND
103958  18.316636 -64.889156  ST. THOMAS ISLAND

[103959 rows x 3 columns]

In [34]:
school_dem09.columns = [col[:-2] for col in list(school_dem09.columns)]

In [35]:
school_dem09

,NCESS,FIP,LEA,SCH,STID,SEASCH,LEANM,SCHNAM,PHONE,MSTREE,...,WHALM,WHALF,PACIFIC,HPALM,HPALF,TR,TRALM,TRALF,TOTETH,PUPTCH
0,010000200277,01,0100002,00277,210,0020,ALABAMA YOUTH SERVICES,SEQUOYAH SCH - CHALKVILLE CAMPUS,2056808574,P O BOX 9486,...,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0,0.00
1,010000201402,01,0100002,01402,210,0025,ALABAMA YOUTH SERVICES,EUFAULA SCH - EUFAULA CAMPUS,3346874441,315 OUTBACK ROAD,...,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0,0.00
2,010000201667,01,0100002,01667,210,0050,ALABAMA YOUTH SERVICES,CAMPS,3342153850,P O BOX 66,...,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0,0.00
3,010000201670,01,0100002,01670,210,0060,ALABAMA YOUTH SERVICES,DET CTR,3342153850,P O BOX 66,...,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0,0.00
4,010000201705,01,0100002,01705,210,0030,ALABAMA YOUTH SERVICES,WALLACE SCH - MT MEIGS CAMPUS,3342156039,P O BOX 66,...,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103954,780003000025,78,7800030,00025,001,21,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,GLADYS A. ABRAHAM ELEMENTARY SCHOOL,3407747385,68A ESTATE LINDBERG,...,8.0,7.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,414.0,12.55
103955,780003000026,78,7800030,00026,001,17,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,ULLA F MULLER ELEMENTARY SCHOOL,3407740059,7B ESTATE CONTANT,...,9.0,11.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,404.0,14.55
103956,780003000027,78,7800030,00027,001,23,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,YVONNE BOWSKY ELEMENTARY SCHOOL,3407753220,15B & 16 ESTATE MANDAHL,...,6.0,5.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,428.0,15.29
103957,780003000033,78,7800030,00033,001,25,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,CANCRYN JUNIOR HIGH SCHOOL,3407744540,1 CROWN BAY,...,0.0,1.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,584.0,11.04
103958,780003000034,78,7800030,00034,001,9,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,BERTHA BOSCHULTE JUNIOR HIGH,3407754222,9-1 & 12A BOVONI (WESTERN),...,1.0,1.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,606.0,11.65

In [38]:
school_dem09['ULOCAL'].value_counts()

21    23553
11    13867
41    13843
42    11988
32     7392
43     7335
13     7189
12     6009
33     5182
22     3001
31     2051
23     1998
N       469
M        82
Name: ULOCAL, dtype: int64

In [54]:
enroll09_cols = [school_dem09.columns[0]] + list(school_dem09.columns[41:289])
enroll09_cols

['NCESS',
 'PK',
 'AMPKM',
 'AMPKF',
 'ASPKM',
 'ASPKF',
 'HIPKM',
 'HIPKF',
 'BLPKM',
 'BLPKF',
 'WHPKM',
 'WHPKF',
 'HPPKM',
 'HPPKF',
 'TRPKM',
 'TRPKF',
 'KG',
 'AMKGM',
 'AMKGF',
 'ASKGM',
 'ASKGF',
 'HIKGM',
 'HIKGF',
 'BLKGM',
 'BLKGF',
 'WHKGM',
 'WHKGF',
 'HPKGM',
 'HPKGF',
 'TRKGM',
 'TRKGF',
 'G01',
 'AM01M',
 'AM01F',
 'AS01M',
 'AS01F',
 'HI01M',
 'HI01F',
 'BL01M',
 'BL01F',
 'WH01M',
 'WH01F',
 'HP01M',
 'HP01F',
 'TR01M',
 'TR01F',
 'G02',
 'AM02M',
 'AM02F',
 'AS02M',
 'AS02F',
 'HI02M',
 'HI02F',
 'BL02M',
 'BL02F',
 'WH02M',
 'WH02F',
 'HP02M',
 'HP02F',
 'TR02M',
 'TR02F',
 'G03',
 'AM03M',
 'AM03F',
 'AS03M',
 'AS03F',
 'HI03M',
 'HI03F',
 'BL03M',
 'BL03F',
 'WH03M',
 'WH03F',
 'HP03M',
 'HP03F',
 'TR03M',
 'TR03F',
 'G04',
 'AM04M',
 'AM04F',
 'AS04M',
 'AS04F',
 'HI04M',
 'HI04F',
 'BL04M',
 'BL04F',
 'WH04M',
 'WH04F',
 'HP04M',
 'HP04F',
 'TR04M',
 'TR04F',
 'G05',
 'AM05M',
 'AM05F',
 'AS05M',
 'AS05F',
 'HI05M',
 'HI05F',
 'BL05M',
 'BL05F',
 'WH05M',
 'WH05F',
 'HP05M',
 'HP05F',
 'TR05M',
 'TR05F',
 'G06',
 'AM06M',
 'AM06F',
 'AS06M',
 'AS06F',
 'HI06M',
 'HI06F',
 'BL06M',
 'BL06F',
 'WH06M',
 'WH06F',
 'HP06M',
 'HP06F',
 'TR06M',
 'TR06F',
 'G07',
 'AM07M',
 'AM07F',
 'AS07M',
 'AS07F',
 'HI07M',
 'HI07F',
 'BL07M',
 'BL07F',
 'WH07M',
 'WH07F',
 'HP07M',
 'HP07F',
 'TR07M',
 'TR07F',
 'G08',
 'AM08M',
 'AM08F',
 'AS08M',
 'AS08F',
 'HI08M',
 'HI08F',
 'BL08M',
 'BL08F',
 'WH08M',
 'WH08F',
 'HP08M',
 'HP08F',
 'TR08M',
 'TR08F',
 'G09',
 'AM09M',
 'AM09F',
 'AS09M',
 'AS09F',
 'HI09M',
 'HI09F',
 'BL09M',
 'BL09F',
 'WH09M',
 'WH09F',
 'HP09M',
 'HP09F',
 'TR09M',
 'TR09F',
 'G10',
 'AM10M',
 'AM10F',
 'AS10M',
 'AS10F',
 'HI10M',
 'HI10F',
 'BL10M',
 'BL10F',
 'WH10M',
 'WH10F',
 'HP10M',
 'HP10F',
 'TR10M',
 'TR10F',
 'G11',
 'AM11M',
 'AM11F',
 'AS11M',
 'AS11F',
 'HI11M',
 'HI11F',
 'BL11M',
 'BL11F',
 'WH11M',
 'WH11F',
 'HP11M',
 'HP11F',
 'TR11M',
 'TR11F',
 'G12',
 'AM12M',
 'AM12F',
 'AS12M',
 'AS12F',
 'HI12M',
 'HI12F',
 'BL12M',
 'BL12F',
 'WH12M',
 'WH12F',
 'HP12M',
 'HP12F',
 'TR12M',
 'TR12F',
 'UG',
 'AMUGM',
 'AMUGF',
 'ASUGM',
 'ASUGF',
 'HIUGM',
 'HIUGF',
 'BLUGM',
 'BLUGF',
 'WHUGM',
 'WHUGF',
 'HPUGM',
 'HPUGF',
 'TRUGM',
 'TRUGF',
 'MEMBER',
 'AM',
 'AMALM',
 'AMALF',
 'ASIAN',
 'ASALM',
 'ASALF',
 'HISP',
 'HIALM',
 'HIALF',
 'BLACK',
 'BLALM',
 'BLALF',
 'WHITE',
 'WHALM',
 'WHALF',
 'PACIFIC',
 'HPALM',
 'HPALF',
 'TR',
 'TRALM',
 'TRALF',
 'TOTETH']

In [55]:
school_dem09[enroll09_cols].set_index('NCESS')

,PK,AMPKM,AMPKF,ASPKM,ASPKF,HIPKM,HIPKF,BLPKM,BLPKF,WHPKM,...,WHITE,WHALM,WHALF,PACIFIC,HPALM,HPALF,TR,TRALM,TRALF,TOTETH
NCESS,,,,,,,,,,,,,,,,,,,,,
010000200277,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0
010000201402,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0
010000201667,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0
010000201670,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0
010000201705,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780003000025,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,15.0,8.0,7.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,414.0
780003000026,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,20.0,9.0,11.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,404.0
780003000027,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,11.0,6.0,5.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,428.0
780003000033,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,1.0,0.0,1.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,584.0
780003000034,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,2.0,1.0,1.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,606.0

In [56]:
dem_cols = list(school_dem09.columns[:42])+list(school_dem09.columns[288:])

In [57]:
dem_cols

['NCESS',
 'FIP',
 'LEA',
 'SCH',
 'STID',
 'SEASCH',
 'LEANM',
 'SCHNAM',
 'PHONE',
 'MSTREE',
 'MCITY',
 'MSTATE',
 'MZIP',
 'MZIP4',
 'LSTREE',
 'LCITY',
 'LSTATE',
 'LZIP',
 'LZIP4',
 'TYPE',
 'STATUS',
 'ULOCAL',
 'LATCOD',
 'LONCOD',
 'CONUM',
 'CONAME',
 'CDCODE',
 'FTE',
 'GSLO',
 'GSHI',
 'LEVEL',
 'TITLEI',
 'STITLI',
 'MAGNET',
 'CHARTR',
 'SHARED',
 'BIES',
 'FRELCH',
 'REDLCH',
 'TOTFRL',
 'RACECAT',
 'PK',
 'TOTETH',
 'PUPTCH']